# Generated by Django 2.0.1 on 2018-01-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=36)),
                ('redirect_uri', models.URLField()),
            ],
            options={
                'verbose_name': 'OAuth2 Client',
                'db_table': 'lumiere_clients',
                'managed': True,
            },
        ),
    ]
